import "./app";
import "./commonStyle/common.css";
import "./commonStyle/buttons.css";
import "./components/forms/css/sendForm.css";
import "./components/forms/css/sendTextForm.css";
import "./components/forms/css/sendFileForm.css";
import "./components/contentView/contentView.css";
import "./components/message/message.css";
import "./components/changeDateMessage/changeDateMessage.css";
import "./components/navigator/navigator.css";
import "./components/messageOptions/messageOptions.css";
import "./components/contentMessage/contentMessage.css";
import "./components/pinMMessage/pinMessage.css";
import "./components/forms/css/searchForm.css";
import "./components/message/progressBar.css"
